/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        heading: ['"Rubik"', "sans-serif"],
        body: ['"Nunito Sans"', "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        grosir: {
          primary: "#059669",
          "primary-content": "#ffffff",
          secondary: "#3b82f6",
          "secondary-content": "#ffffff",
          accent: "#f59e0b",
          "accent-content": "#000000",
          neutral: "#374151",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f0fdf4",
          "base-300": "#dcfce7",
          "base-content": "#1f2937",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#10b981",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-content": "#ffffff",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--animation-btn": "0.15s",
          "--btn-focus-scale": "0.97",
        },
      },
      {
        "grosir-dark": {
          primary: "#10b981",
          "primary-content": "#000000",
          secondary: "#60a5fa",
          "secondary-content": "#000000",
          accent: "#fbbf24",
          "accent-content": "#000000",
          neutral: "#9ca3af",
          "neutral-content": "#000000",
          "base-100": "#0f172a",
          "base-200": "#1e293b",
          "base-300": "#334155",
          "base-content": "#e2e8f0",
          info: "#60a5fa",
          "info-content": "#000000",
          success: "#34d399",
          "success-content": "#000000",
          warning: "#fbbf24",
          "warning-content": "#000000",
          error: "#f87171",
          "error-content": "#000000",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--animation-btn": "0.15s",
          "--btn-focus-scale": "0.97",
        },
      },
    ],
  },
};
